---
server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  profiles: subject
words: I,You,He,She,It
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
---
spring:
  profiles: article
words: a,the
---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
---
spring:
  profiles: sentence
server:
  port: 8020
---
spring:
  profiles: gateway
server:
  port: 8080
